# Generated by Django 2.1.7 on 2019-02-19 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['film_title'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(null=True)),
                ('review', models.TextField()),
                ('review_film', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='film_info.Film')),
            ],
        ),
    ]
