# Generated by Django 2.1.7 on 2019-02-12 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['-film_title']},
        ),
    ]
