# Generated by Django 2.1.7 on 2019-02-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0002_auto_20190212_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ['film_title']},
        ),
    ]
