# Generated by Django 2.1.7 on 2019-02-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0003_upost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upost',
            name='approved_comment',
        ),
    ]
