# Generated by Django 2.1.7 on 2019-02-23 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0004_remove_upost_approved_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upost',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_info.Film'),
        ),
    ]
