# Generated by Django 2.1.7 on 2019-02-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0005_auto_20190223_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='upost',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film_info.Ucomment'),
        ),
    ]
