# Generated by Django 2.1.7 on 2019-02-26 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0006_auto_20190223_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='film_info.Comment')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='upost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='upost',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Ucomment',
        ),
        migrations.DeleteModel(
            name='Upost',
        ),
    ]
