# Generated by Django 2.1.7 on 2019-02-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0007_auto_20190226_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='posted',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('timestamp',)},
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
