# Generated by Django 2.1.7 on 2019-03-01 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0012_auto_20190301_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
