# Generated by Django 2.1.7 on 2019-03-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_info', '0016_auto_20190302_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movies/media'),
        ),
    ]
